#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

#picom 
pkill picom
picom -b &
#picom --expiremental-backends --no-use-damage &

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &


# Set HDMI0 as the primary display and disable other displays
xrandr --output HDMI-1 --auto --primary --output eDP-1 --auto --rotate right --left-of HDMI-1
 --output HDMI-1 --mode 1366x768 --pos 0x1080 --rotate normal --output DP-0 --off --output DP-1 --off --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate right --left-of HDMI-1 --output VIRTUAL1 --off
 --output eDP-1 --rotate right
 --output HDMI-1 --primary
bspc wm -O HDMI-1 eDP-1



# wallpaper

feh --bg-fill ~/Pictures/cactus.jpeg &

# panel
#tint2 &
bash ~/.config/polybar/launch.sh --forest &



bspc monitor -d 0 1 2 3 4 5
## Bspwm colors
BSPWM_FBC='#81A1C1'
BSPWM_NBC='#2E3440'
BSPWM_ABC='#B48EAD'
BSPWM_PFC='#A3BE8C'

## Bspwm appearance
BSPWM_BORDER='0'
BSPWM_GAP='2'
BSPWM_SRATIO='0.50'

#

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true






